baseURL = "https://behroozshahri.com/"
languageCode = "en-us"
title = "Behrooz Shahri"
theme = "alexa-portfolio"
googleAnalytics = "UA-167869327-1"
enableRobotsTXT = true
relURL = "https://behroozshahri.com/"

[params]
	# favicon = "/images/fav.png"
	home_title = "I’m Behrooz Shahri"
	home_subtitle = "Turning Passion Into Action"
	home_description = "I’ve spent over 12 years building startups and helping businesses succeed. I love turning creative ideas into practical results, making work meaningful, and keeping things human and fun along the way."
	# Path to the homepage profile image served from /static (no leading slash for rel/absURL)
	home_image = "images/profile.png"
	github = "https://github.com/bonaxcrimo"
	linkedin = "https://www.linkedin.com/in/behrooz-shahri/"
	dribbble = "https://dribbble.com/RainMustbeDark"
	phone = "+971557886743"
	email = "behroozshahri@gmail.com"
	location = "Dubai, UAE"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true